# Generated by Django 2.1.8 on 2019-04-13 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTagRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.Image')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='imagetagrelationship',
            unique_together={('image', 'tag')},
        ),
    ]
